/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ymcris.ipc1.exercises.Practica2Practica;
import javax.swing.ImageIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JToggleButton;
/**
 *
 * @author crist
 */
public class NewClass extends javax.swing.JFrame {
    private JToggleButton[] botonesSeleccionados = new JToggleButton[2];
    private static final String parejaOculta = "/parejaOculta.png";
    private static final String pareja1 = "/pareja1.png";
    private static final String pareja2 = "/pareja2.png";
    private static final String pareja3 = "/pareja3.png";
    private static final String pareja4 = "/pareja4.png";
    private static final String pareja5 = "/pareja5.png";
    /**
     * Creates new form Pantalla
     */
    public NewClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        carta2 = new javax.swing.JToggleButton();
        carta3 = new javax.swing.JToggleButton();
        carta1 = new javax.swing.JToggleButton();
        carta11 = new javax.swing.JToggleButton();
        carta22 = new javax.swing.JToggleButton();
        carta33 = new javax.swing.JToggleButton();
        carta4 = new javax.swing.JToggleButton();
        carta5 = new javax.swing.JToggleButton();
        carta55 = new javax.swing.JToggleButton();
        carta44 = new javax.swing.JToggleButton();
        jlabelTurno = new javax.swing.JLabel();
        jlabelPunteoJugador1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setText("HolaMundo");

        jLabel2.setText("Ingrese texto");

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        jLabel3.setText("El texto que usted ingreso es:");

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        btn.setText("Copiar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        btn2.setText("Limpiar");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 233, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn2)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        carta2.setForeground(new java.awt.Color(187, 187, 200));
        carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parejaOculta.png"))); // NOI18N
        carta2.setText("Carta2");
        carta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta2ActionPerformed(evt);
            }
        });

        carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parejaOculta.png"))); // NOI18N
        carta3.setText("Carta3");
        carta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta3ActionPerformed(evt);
            }
        });

        carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parejaOculta.png"))); // NOI18N
        carta1.setText("Carta1");
        carta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta1ActionPerformed(evt);
            }
        });

        carta11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parejaOculta.png"))); // NOI18N
        carta11.setText("Carta1");
        carta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta11ActionPerformed(evt);
            }
        });

        carta22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parejaOculta.png"))); // NOI18N
        carta22.setText("Carta2");
        carta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta22ActionPerformed(evt);
            }
        });

        carta33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parejaOculta.png"))); // NOI18N
        carta33.setText("Carta3");
        carta33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta33ActionPerformed(evt);
            }
        });

        carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parejaOculta.png"))); // NOI18N
        carta4.setText("Carta4");
        carta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta4ActionPerformed(evt);
            }
        });

        carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parejaOculta.png"))); // NOI18N
        carta5.setText("Carta5");
        carta5.setToolTipText("");
        carta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta5ActionPerformed(evt);
            }
        });

        carta55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parejaOculta.png"))); // NOI18N
        carta55.setText("Carta5");
        carta55.setToolTipText("");
        carta55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta55ActionPerformed(evt);
            }
        });

        carta44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parejaOculta.png"))); // NOI18N
        carta44.setText("Carta4");
        carta44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta44ActionPerformed(evt);
            }
        });

        jlabelTurno.setText("TURNO DE:");

        jlabelPunteoJugador1.setText("PUNTEO DE ");

        jLabel4.setText("PUNTEO DE");

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(true);
        jToolBar1.setRollover(true);

        jButton1.setText("AYUDA");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("REPORTES");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setText("JUGAR NUEVA PARTIDA");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelPunteoJugador1)
                    .addComponent(jLabel4)
                    .addComponent(jlabelTurno))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(carta11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta33, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta44, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta55, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jlabelTurno)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(carta44, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carta55, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(carta11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carta22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carta33, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jlabelPunteoJugador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
        carta1.addActionListener(new BotonActionListener());
        carta2.addActionListener(new BotonActionListener());
        carta3.addActionListener(new BotonActionListener());
        carta4.addActionListener(new BotonActionListener());
        carta5.addActionListener(new BotonActionListener());
        carta11.addActionListener(new BotonActionListener());
        carta22.addActionListener(new BotonActionListener());
        carta33.addActionListener(new BotonActionListener());
        carta44.addActionListener(new BotonActionListener());
        carta55.addActionListener(new BotonActionListener());
    }// </editor-fold>    
private class BotonActionListener implements ActionListener {
    @Override
    public void actionPerformed(ActionEvent e) {
        JToggleButton boton = (JToggleButton) e.getSource();
        
        if (boton.isSelected()) {
            // Si ya hay dos botones seleccionados, deseleccionar los dos anteriores dos veces
            if (botonesSeleccionados[0] != null && botonesSeleccionados[1] != null) {
                botonesSeleccionados[0].setSelected(false); // Deselecciona el primer botón dos veces
                botonesSeleccionados[1].setSelected(false); // Deselecciona el segundo botón dos veces

            }
            // Mover los botones hacia adelante en el array
            botonesSeleccionados[0] = botonesSeleccionados[1];
            botonesSeleccionados[1] = boton;
        } else {
            // Si se deselecciona un botón, ajustar el array
            if (boton == botonesSeleccionados[0]) {
                botonesSeleccionados[0] = null;
            } else if (boton == botonesSeleccionados[1]) {
                botonesSeleccionados[1] = null;
            }
        }
    }
}



    /**
     * 
     * @param args 
     */
    public static void main(String[] args) {
        NewClass pantalla = new NewClass();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
    }

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        initComponents();
        
    }                                    

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {                                    
        
        txt2.setText(txt1.getText());
    }                                   

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        txt1.setText("");
        txt2.setText("");
    }                                    

    private void carta2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (carta2.isSelected()) {
            carta2.setIcon(new ImageIcon(getClass().getResource(pareja2)));
        } else {
            
            carta2.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
        }
        
        
        
        
        /*if (cartaPareja2.isSelected()){
            cartaPareja2.setIcon(new ImageIcon(getClass().getResource(pareja1)));
        }else{
            cartaPareja2.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
        }*/
    }                                      

    private void carta1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        carta1.isSelected();
        if (carta1.isSelected()) {
            carta1.setIcon(new ImageIcon(getClass().getResource(pareja1)));
        } else {
            
            carta1.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
        }
        
        /* if(Pareja1.isSelected()){
            Menu menu = new Menu();
            menu.setVisible(true);
        }else {
            System.out.println("Holapepe");
        }*/
    }                                      

    private void carta3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (carta3.isSelected()) {
            carta3.setIcon(new ImageIcon(getClass().getResource(pareja3)));
        } else {
            carta3.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
            
        }
        
    }                                      
    /**carta1ActionPerformed. Asigna imagenes a la carta
     * 
     * @param evt 
     */
    private void carta11ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (carta11.isSelected()) {
            carta11.setIcon(new ImageIcon(getClass().getResource(pareja1)));
        } else {
            carta11.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
            
        }
        
    }                                       

    private void carta22ActionPerformed(java.awt.event.ActionEvent evt) {                                        
          if (carta22.isSelected()) {
            carta22.setIcon(new ImageIcon(getClass().getResource(pareja2)));
        } else {
              carta22.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
            
        }
        
    }                                       

    private void carta33ActionPerformed(java.awt.event.ActionEvent evt) {                                        
          if (carta33.isSelected()) {
            carta33.setIcon(new ImageIcon(getClass().getResource(pareja3)));
        } else {
              carta33.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
            
        }
        
    }                                       

    private void carta4ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (carta4.isSelected()) {
            carta4.setIcon(new ImageIcon(getClass().getResource(pareja4)));
        } else {
            carta4.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
            
        }
        
    }                                      

    private void carta5ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (carta5.isSelected()) {
            carta5.setIcon(new ImageIcon(getClass().getResource(pareja5)));
        } else {
            carta5.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
            
        }
        
    }                                      

    private void carta55ActionPerformed(java.awt.event.ActionEvent evt) {                                        
          if (carta55.isSelected()) {
            carta55.setIcon(new ImageIcon(getClass().getResource(pareja5)));
        } else {
              carta55.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
            
        }
        
    }                                       

    private void carta44ActionPerformed(java.awt.event.ActionEvent evt) {                                        
          if (carta44.isSelected()) {
            carta44.setIcon(new ImageIcon(getClass().getResource(pareja4)));
        } else {
            
            carta44.setIcon(new ImageIcon(getClass().getResource(parejaOculta)));
        }
        
    }                                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify                     
    private javax.swing.JButton btn;
    private javax.swing.JButton btn2;
    private javax.swing.JToggleButton carta1;
    private javax.swing.JToggleButton carta11;
    private javax.swing.JToggleButton carta2;
    private javax.swing.JToggleButton carta22;
    private javax.swing.JToggleButton carta3;
    private javax.swing.JToggleButton carta33;
    private javax.swing.JToggleButton carta4;
    private javax.swing.JToggleButton carta44;
    private javax.swing.JToggleButton carta5;
    private javax.swing.JToggleButton carta55;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jlabelPunteoJugador1;
    private javax.swing.JLabel jlabelTurno;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration                   
}
